CREATE OR REPLACE PACKAGE GAMEPACKAGE IS
FUNCTION GENERATE_RANDOM_NUMBER RETURN NUMBER;
FUNCTION CHECKFORWIN(USERLOGIN IN VARCHAR2, BETID IN NUMBER, WINNUMBER NUMBER) RETURN VARCHAR2;
FUNCTION PLAYGAME(LOGIN IN VARCHAR2, WINNUM IN NUMBER DEFAULT NULL) RETURN VARCHAR2;
END GAMEPACKAGE;
/
CREATE OR REPLACE PACKAGE BODY GAMEPACKAGE IS
FUNCTION GENERATE_RANDOM_NUMBER RETURN NUMBER IS
RAND NUMBER;
BEGIN
    SELECT ROUND(DBMS_RANDOM.VALUE(0,36)) INTO RAND FROM DUAL;
    DBMS_OUTPUT.PUT_LINE(RAND);
    RETURN RAND;
END GENERATE_RANDOM_NUMBER;

FUNCTION PLAYGAME(LOGIN IN VARCHAR2, WINNUM IN NUMBER DEFAULT NULL) RETURN VARCHAR2  IS
WINNUMBER NUMBER;
RES VARCHAR2(30);
FAILCOUNT NUMBER:=0;
COUNTER NUMBER;
BEGIN
IF WINNUM IS NULL THEN
    WINNUMBER := GAMEPACKAGE.GENERATE_RANDOM_NUMBER();
    ELSE WINNUMBER:=WINNUM;
    END IF;
    FOR CURR IN (SELECT BET_ID FROM CASINO WHERE USER_LOGIN=LOGIN) LOOP

        RES:=GAMEPACKAGE.CHECKFORWIN(LOGIN, CURR.BET_ID, WINNUMBER); 
    
     IF RES = 'FALSE' THEN FAILCOUNT:=FAILCOUNT+1;
     END IF;
    END LOOP;
    SELECT COUNT(BET_ID) INTO COUNTER FROM CASINO WHERE USER_LOGIN=LOGIN;
    IF FAILCOUNT < COUNTER THEN
         RES:='TRUE';
    ELSE RES:='FALSE';
    END IF;
    RETURN RES;
END PLAYGAME;

FUNCTION CHECKFORWIN(USERLOGIN IN VARCHAR2, BETID IN NUMBER , WINNUMBER NUMBER) RETURN VARCHAR2 IS
BETCOUNTER NUMBER:=0;
BET_FIELD NUMBER;
MONEY NUMBER;
MULT NUMBER;
RES VARCHAR2(100);

BEGIN

    SELECT COUNT(BET_ID) INTO BETCOUNTER FROM CASINO WHERE USER_LOGIN=USERLOGIN;
    IF BETCOUNTER = 0 THEN RETURN 'NO BET';
    END IF;
    SELECT BET_NAME INTO BET_FIELD FROM BET WHERE BET_ID=BETID;
    SELECT BET_MONEY INTO MONEY FROM BET WHERE BET_ID=BETID;
    SELECT BET_MULTIPLIER INTO MULT FROM BET WHERE BET_ID=BETID;
    IF BET_FIELD=WINNUMBER THEN USERPACKAGE.CHANGE_PLAYER_BALANCE(USERLOGIN, MONEY*MULT); RES:='TRUE';
    ELSE RES:='FALSE';
    BETPACKAGE.DELETE_BET(BETID);
    RETURN RES;
    END IF;
END CHECKFORWIN;
END GAMEPACKAGE;
