/*POPULATE DATABASE */
INSERT INTO "USER" (USER_LOGIN, USER_PASSWORD, USER_NAME, USER_AGE, USER_EMAIL)
VALUES('Dima', 'dimapass', 'Dmitry', '20', 'dima@example.com');
INSERT INTO "USER" (USER_LOGIN, USER_PASSWORD, USER_NAME, USER_AGE, USER_EMAIL)
VALUES('ColdZero', '123456', 'UserName', '21', 'user@gmail.com');
INSERT INTO "USER" (USER_LOGIN, USER_PASSWORD, USER_NAME, USER_AGE, USER_EMAIL)
VALUES('Login', 'password', 'Alex', '32', 'alex@ukr.net');

INSERT INTO BANKINFO (BANKINFO_CARD_NUMBER,BANKINFO_EXPIRATION_DATE,BANKINFO_ADRESS, USER_LOGIN)
VALUES (4790300014230000, TO_DATE('2023/05/03', 'yyyy/mm/dd'), 'Salutna 4a','Dima');
INSERT INTO BANKINFO (BANKINFO_CARD_NUMBER,BANKINFO_EXPIRATION_DATE,BANKINFO_ADRESS, USER_LOGIN)
VALUES (4935870093456666, TO_DATE('2025/08/31', 'yyyy/mm/dd'), 'Salutna 4a','Dima');
INSERT INTO BANKINFO (BANKINFO_CARD_NUMBER,BANKINFO_EXPIRATION_DATE,BANKINFO_ADRESS, USER_LOGIN)
VALUES (1234567891011123, TO_DATE('2018/12/31', 'yyyy/mm/dd'), 'Krasnodarska 5','Login');
INSERT INTO BANKINFO (BANKINFO_CARD_NUMBER,BANKINFO_EXPIRATION_DATE,BANKINFO_ADRESS, USER_LOGIN)
VALUES (2790600004244316, TO_DATE('2023/05/03', 'yyyy/mm/dd'), null ,'ColdZero');

INSERT INTO BET (BET_ID, BET_MONEY, BET_MULTIPLIER, BET_DATE)
VALUES (0,200,2,TO_DATE('2018/11/11', 'yyyy/mm/dd'));
INSERT INTO BET(BET_ID, BET_MONEY, BET_MULTIPLIER, BET_DATE)
VALUES (1, 100, 3,TO_DATE('2018/11/11', 'yyyy/mm/dd'));
INSERT INTO BET (BET_ID, BET_MONEY, BET_MULTIPLIER, BET_DATE)
VALUES (2,500,5,TO_DATE('2018/11/12', 'yyyy/mm/dd'));
INSERT INTO BET(BET_ID, BET_MONEY, BET_MULTIPLIER, BET_DATE)
VALUES (3,1000,2,TO_DATE('2018/11/11', 'yyyy/mm/dd'));

INSERT INTO CASINO (USER_LOGIN,BET_ID,BET_DATE)
VALUES ('Dima',0,(Select BET_DATE FROM BET WHERE BET.BET_ID=0));
INSERT INTO CASINO (USER_LOGIN,BET_ID,BET_DATE)
VALUES ('Dima',1,(Select BET_DATE FROM BET WHERE BET.BET_ID=1));
INSERT INTO CASINO (USER_LOGIN,BET_ID,BET_DATE)
VALUES ('ColdZero',3,(Select BET_DATE FROM BET WHERE BET.BET_ID=3));
